<div class="header-top">
    <a href="<?php echo $this->getHomeLink() ?>" class="logo">SEMI 后台管理系统</a>
    <div class="header-right">
        <p class="super">
            <?php echo $this->__("Logged in as %s", $this->escapeHtml($this->getUser()->getUsername())) ?><span class="separator">|</span><?php echo $this->formatDate(null, 'full') ?><span class="separator">|</span><a href="<?php echo $this->getLogoutLink() ?>" class="link-logout"><?php echo $this->__('Log Out') ?></a>
        </p>
        
    </div>
</div>
