<?php $_processes = $this->getCacheTypesForRefresh()?>
<?php if($_processes):?>
<div class="notification-global">
    <strong><?php echo $this->helper('adminhtml')->__('One or more of the Cache Types are invalidated:') ?></strong>
    <?php echo implode(', ', $_processes)?>.
    <?php echo $this->helper('adminhtml')->__('Click here to go to <a href="%s">Cache Management</a> and refresh cache types.', $this->getManageUrl());?>
</div>
<?php endif;?>
